### PR TITLE
Add a cool leaderboard to the "Kultainen testauskoira" award ceremony

### PR DESCRIPTION
**Pull request by lajp**
Please read this through carefully since I was unable to test the "Testauskoira" because I was unable to initialize a "Testausdatabase" of my own. Also I'm not that familiar with sql.

### CODE REVIEW

**Review by ahnl — CHANGES_REQUESTED** [review]
Could you run auto indentation through the file? The indentations look very off.

**Comment by lajp** [comment]
OK, will do

**Comment by lajp** [comment]
I'm quite sure the top hunk of the commit was unintentional, perhaps i forgot to rebase or something...

**Review by ahnl — APPROVED** [review]

**Comment by ahnl** [comment]
Thank you for your contribution! The new embed looks awesome.

**Pull request merged**
